---
# Date: 2025-03-21
# Description: Playbook to auto setup hosts on PiHole
# Author: Lucas Janin

- name: Auto setup hosts on PiHole
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Ansible Role Pihole DNS Records Manager
      ansible.builtin.include_role:
        name: ansible-role-pihole-dns-reccords-manager
